eureka:
  client:
    service-url:
      # default to localhost so dev "just works" even if EUREKA_URL is not set
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  cloud:
    config:
      override-system-properties: false
