spring:
  application:
    name: go-league-service
  config:
    import: optional:configserver:http://localhost:8889

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
