spring:
  application:
    name: go-team-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8889}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
